### ISSUE TITLE
Requests

### ISSUE THREAD

**Issue by camejuanm** [ghofaralhasyim/perapian#1]
- [x] Add copy to clipboard button for API key and API URL
- [x] Fix redirect to dashboard
- [x] Fix url route name (use /dashboard instead of /perapian)
- [x] Fix sidebar toggle
- [x] typo "environtment" should be environment
- [x] Fix environment not changing
- [x] Fix sitename field auto capitalization
- [x] header example could automatically show current api key (would be nice to have copy to clipboard too)
- [ ] show correct api example automatically in /perapian/blog
- [x] fix 'Published' and 'Highlight' UI
- [x] edit tags page doesn't show current tag

**Comment by ghofaralhasyim** [comment]
Hi @camejuanm , thank you for submitting your feedback. The website has already been updated.
